server:
  port: 8081

spring:
  application:
    name: rest manager
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

logging:
  level:
    br:
      com:
        posfiap:
          restmanager: DEBUG

# Local
#spring:
#  application:
#    name: rest manager
#  datasource:
#    url: jdbc:postgresql://localhost:5433/restdb
#    username: postgres
#    password: 123456
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgresSQLDialect
#      ddl-auto: update
#    show-sql: true